### ISSUE TITLE
Buttons should be greyed out when disabled

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#2]
When a button is disabled (e.g. can't Stop a tune when no tune is playing), it should be visually greyed out, so the user can easily see which buttons are available.

Usually this greying out is automatic in Windows Forms, but for some reason it isn't happening. I thought it might relate to the buttons having FlatStyle=Popup, but that doesn't seem to be the cause.

One option might be to use a ToolStrip (like a toolbar with multiple buttons on it) instead of separate individual Buttons. ToolStrips also allow easily adding other controls like dropdown lists etc.

**Comment by equin0x80** [comment]
I think it's because the images have been set as Button.BackgroundImage and not the usual Button.Image property. This was apparently done because they did not align properly otherwise.

Possible fixes for this might be to use the ButtonBase.ImageAlign property, or something with Padding [as described here](https://stackoverflow.com/questions/37755930/difficulty-centering-image-on-c-sharp-winform-button).

**Comment by equin0x80** [comment]
I need the image files with the button icons, e.g. play icon, shuffle icon. Can these be added to the project in a subfolder?

**Comment by DietmarKlein** [comment]
Uploaded them to the #dev on discord

**Comment by equin0x80** [comment]
I see... it's a mixed bunch of different formats and sizes, including SVG which doesn't have a native size. I only know how to work with ICO. So I can't fix this, sorry.

**Comment by DietmarKlein** [comment]
Its okay. Its icons from iconmonstr and I created some icons on my own based on their icons which I saved as .psd methinks. No worries
