### ISSUE TITLE
Song sometimes doesn't stop playing on exit

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#3]
I thought I had possibly fixed this but no, it still sometimes happens -- not always.  I have no idea why.  It is quite annoying because you have to open Task Manager and find the separate player process to shut it down.

Ideally we would find a way to play/stop songs without using a separate executable process, but I don't know if that's possible.

**Comment by DietmarKlein** [comment]
Well if we could manage to get ahold of the sidplay DLLs dokumentation, we could possibly play (emulate) the sids ourselves. That would also fix the focus lost issue when a new song is started by Sidtool in the background. However using C++ DLLs in C# is beyond me. 
We should still kill all processes by the same name but that would cause potential data loss for people working wiht a 2nd emulator instance. So for now this is a known issue.

**Comment by equin0x80** [comment]
Here's an automatically generated dump of the available functions in libsidplay2.dll:
[libsidplay_functions.txt](https://github.com/DietmarKlein/sidtool2/files/6369361/libsidplay_functions.txt)

**Comment by equin0x80** [comment]
Alternatively there's a SidplaySharp C# wrapper library here, which we could try:
https://github.com/lioncash/SidplaySharp

**Comment by DietmarKlein** [comment]
Okay the wrapper sounds interesting. However I still don't feel too well with this Covid crap, so I pass on bigger issues atm. But if you want to check it out feel free to give it a go.

**Comment by DietmarKlein** [comment]
Ok the wrapper doesnt work as we found out by now. The problem mainly occurs when debugging as far as I can see so methinks we can leave it as it is for now
