### ISSUE TITLE
Cancelling initial HVSC folder picker causes errors

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#4]
The first time you run SidTool (before you have any saved settings), it prompts for the HVSC folder.  If you cancel that prompt, it continues to the player anyway, and then you get all kinds of errors if you try to do anything.

So we either need better error handling, or just abort the application if they don't choose an HVSC folder at startup when prompted.  (But would that prevent using the app in other ways, e.g. playlists without HVSC?)

**Comment by DietmarKlein** [comment]
I just pushed an update. Sidtool will now exit if you cancel the HVSC folder setup.
If you dont set the HVSC Path there is nothing you can do with the tool, so its manadatory. Thus I think its safe to exit when the user cancels this.
