### ISSUE TITLE
Store user settings in LocalApplicationData?

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#5]
Currently, the sidtool.ini file is stored in the same folder as the application's exe file.

Storing settings in the app's folder is rather old-fashioned, and some people might not even allow apps to write into an installation folder (by setting permissions). It also forces every user on a system to share the same settings.

A more suitable location might be Environment.SpecialFolder.LocalApplicationData ("the directory that serves as a common repository for application-specific data that is used by the current, non-roaming user").

We would need to import the existing settings files of older users who are upgrading.

**Comment by DietmarKlein** [comment]
okay

**Comment by equin0x80** [comment]
Done!

**Comment by DietmarKlein** [comment]
Nice job!
