### ISSUE TITLE
Build Search DB crashes if run twice simultaneously

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#6]
Options > BuildSearchDB now runs in the background.  However, there is nothing to stop you from starting a rebuild when a rebuild is already in progress.  This might corrupt the database file (because two threads would be writing to the same file at once) and it can also cause a crash as follows:

System.InvalidOperationException: 'This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.'

We should probably disable the rebuild menu option until it completes.

**Comment by DietmarKlein** [comment]
Good point. Consider it done.
