### ISSUE TITLE
Upgrade version check is not future-proof

### ISSUE THREAD

**Issue by equin0x80** [DietmarKlein/sidtool2#7]
When upgrading, the client removes the dots from its current version number and compares this with the undotted latest version number from the server. This is only guaranteed to work if every component of the version is a single digit, e.g. 1.2.3.4. Multiple digits may not work, e.g. 1.23.4.5 and 12.3.4.5 would compare identically as 12345.

The maximum component number is 255, so a simple solution would be to pad with zeros before doing the string compare, so that 12.3.4.5 would be "012003004005". It can be done like this:

```
Version v = Assembly.GetExecutingAssembly().GetName().Version;
string padded = v.Major.ToString().PadLeft(3, '0') + v.Minor.ToString().PadLeft(3, '0') + v.Build.ToString().PadLeft(3, '0') + v.Revision.ToString().PadLeft(3, '0');
```

However, if we change this, we may want to change the upgrade check URL, because older versions will still expect to receive the version number in the old (unpadded) format, and will get confused otherwise.

**Comment by DietmarKlein** [comment]
Well with this change we will be on the save side for decades. :) When we are onto this we could also send the current tool version to the server and use some script instead of a plain txt file. This way we can always react to unforeseeable changes and deliver to the tol what it expects.

**Comment by DietmarKlein** [comment]
Added mentioned padded string to SidTool and added script to website to handle the request. There is fake testdata for 2.1.0.1 online until we release a new, real 2.1.0.1
